[workspace]
authors = ["nihildigit <nihildigit@outlook.com>"]
channels = ["conda-forge"]
name = "jm2e"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"

[pypi-dependencies]
jmcomic = "*"
python-telegram-bot = "*"
httpx = "*"
beautifulsoup4 = "*"
lxml = "*"
ehentai = "*"
pykakasi = "*"
opencc-python-reimplemented = "*"
